# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/huawei/g620s/setup-makefiles.sh

PATH_FILES := vendor/huawei/g620s/proprietary

# Bin
PRODUCT_COPY_FILES += \
    $(PATH_FILES)/bin/adsprpcd:system/bin/adsprpcd \
    $(PATH_FILES)/bin/ATFWD-daemon:system/bin/ATFWD-daemon \
    $(PATH_FILES)/bin/bridgemgrd:system/bin/bridgemgrd \
    $(PATH_FILES)/bin/btnvtool:system/bin/btnvtool \
    $(PATH_FILES)/bin/dpmd:system/bin/dpmd \
    $(PATH_FILES)/bin/ds_fmc_appd:system/bin/ds_fmc_appd \
    $(PATH_FILES)/bin/gps_check:system/bin/gps_check \
    $(PATH_FILES)/bin/gpsone_daemon:system/bin/gpsone_daemon \
    $(PATH_FILES)/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    $(PATH_FILES)/bin/imsdatadaemon:system/bin/imsdatadaemon \
    $(PATH_FILES)/bin/imsqmidaemon:system/bin/imsqmidaemon \
    $(PATH_FILES)/bin/ims_rtp_daemon:system/bin/ims_rtp_daemon \
    $(PATH_FILES)/bin/iperf:system/bin/iperf \
    $(PATH_FILES)/bin/irsc_util:system/bin/irsc_util \
    $(PATH_FILES)/bin/iw:system/bin/iw \
    $(PATH_FILES)/bin/iwconfig:system/bin/iwconfig \
    $(PATH_FILES)/bin/iwlist:system/bin/iwlist \
    $(PATH_FILES)/bin/iwpriv:system/bin/iwpriv \
    $(PATH_FILES)/bin/location-mq:system/bin/location-mq \
    $(PATH_FILES)/bin/loc_launcher:system/bin/loc_launcher \
    $(PATH_FILES)/bin/lowi-server:system/bin/lowi-server \
    $(PATH_FILES)/bin/mm-pp-daemon:system/bin/mm-pp-daemon \
    $(PATH_FILES)/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    $(PATH_FILES)/bin/mpdecision:system/bin/mpdecision \
    $(PATH_FILES)/bin/netmgrd:system/bin/netmgrd \
    $(PATH_FILES)/bin/oeminfo_server:system/bin/oeminfo_server \
    $(PATH_FILES)/bin/port-bridge:system/bin/port-bridge \
    $(PATH_FILES)/bin/ptt_socket_app:system/bin/ptt_socket_app \
    $(PATH_FILES)/bin/qcom-system-daemon:system/bin/qcom-system-daemon \
    $(PATH_FILES)/bin/qmiproxy:system/bin/qmiproxy \
    $(PATH_FILES)/bin/qmuxd:system/bin/qmuxd \
    $(PATH_FILES)/bin/qseecomd:system/bin/qseecomd \
    $(PATH_FILES)/bin/radish:system/bin/radish \
    $(PATH_FILES)/bin/rfs_access:system/bin/rfs_access \
    $(PATH_FILES)/bin/rmnetcli:system/bin/rmnetcli \
    $(PATH_FILES)/bin/rmt_oeminfo:system/bin/rmt_oeminfo \
    $(PATH_FILES)/bin/rmt_storage:system/bin/rmt_storage \
    $(PATH_FILES)/bin/subsystem_ramdump:system/bin/subsystem_ramdump \
    $(PATH_FILES)/bin/test_diag:system/bin/test_diag \
    $(PATH_FILES)/bin/test_oeminfo:system/bin/test_oeminfo \
    $(PATH_FILES)/bin/thermal-engine:system/bin/thermal-engine \
    $(PATH_FILES)/bin/time_daemon:system/bin/time_daemon \
    $(PATH_FILES)/bin/usbhub:system/bin/usbhub \
    $(PATH_FILES)/bin/usbhub_init:system/bin/usbhub_init \
    $(PATH_FILES)/bin/usb_uicc_client:system/bin/usb_uicc_client \
    $(PATH_FILES)/bin/vm_bms:system/bin/vm_bms \
    $(PATH_FILES)/bin/wcnss_filter:system/bin/wcnss_filter \
    $(PATH_FILES)/bin/wdsdaemon:system/bin/wdsdaemon \
    $(PATH_FILES)/bin/xtwifi-client:system/bin/xtwifi-client \
    $(PATH_FILES)/bin/xtwifi-inet-agent:system/bin/xtwifi-inet-agent

# Etc
PRODUCT_COPY_FILES += \
    $(PATH_FILES)/etc/firmware/a225_pm4.fw:system/etc/firmware/a225_pm4.fw \
    $(PATH_FILES)/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw \
    $(PATH_FILES)/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw \
    $(PATH_FILES)/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
    $(PATH_FILES)/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
    $(PATH_FILES)/etc/firmware/a330_pfp.fw:system/etc/firmware/a330_pfp.fw \
    $(PATH_FILES)/etc/firmware/a330_pm4.fw:system/etc/firmware/a330_pm4.fw \
    $(PATH_FILES)/etc/firmware/a420_pfp.fw:system/etc/firmware/a420_pfp.fw \
    $(PATH_FILES)/etc/firmware/a420_pm4.fw:system/etc/firmware/a420_pm4.fw \
    $(PATH_FILES)/etc/firmware/cherry_gis_fw.img:system/etc/firmware/cherry_gis_fw.img \
    $(PATH_FILES)/etc/firmware/cherry_ofilm_fw.img:system/etc/firmware/cherry_ofilm_fw.img \
    $(PATH_FILES)/etc/firmware/cherry_yassy_fw.img:system/etc/firmware/cherry_yassy_fw.img \
    $(PATH_FILES)/etc/firmware/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw \
    $(PATH_FILES)/etc/firmware/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw \
    $(PATH_FILES)/etc/firmware/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw \
    $(PATH_FILES)/etc/firmware/cpp_firmware_v1_4_0.fw:system/etc/firmware/cpp_firmware_v1_4_0.fw \
    $(PATH_FILES)/etc/firmware/fused_nvm_y635_cl00.bin:system/etc/firmware/fused_nvm_y635_cl00.bin \
    $(PATH_FILES)/etc/firmware/g620S_junda_fw.img:system/etc/firmware/g620S_junda_fw.img \
    $(PATH_FILES)/etc/firmware/g620S_ofilm_fw.img:system/etc/firmware/g620S_ofilm_fw.img \
    $(PATH_FILES)/etc/firmware/g620S_truly_fw.img:system/etc/firmware/g620S_truly_fw.img \
    $(PATH_FILES)/etc/firmware/g660S_ofilm_fw.img:system/etc/firmware/g660S_ofilm_fw.img \
    $(PATH_FILES)/etc/firmware/g660S_truly_fw.img:system/etc/firmware/g660S_truly_fw.img \
    $(PATH_FILES)/etc/firmware/g760-HB3748B8EBC_FMT_ATL.fw:system/etc/firmware/g760-HB3748B8EBC_FMT_ATL.fw \
    $(PATH_FILES)/etc/firmware/g760-HB3748B8EBC_LS_LS.fw:system/etc/firmware/g760-HB3748B8EBC_LS_LS.fw \
    $(PATH_FILES)/etc/firmware/g760-HB3748B8EBC_XWD_SDI.fw:system/etc/firmware/g760-HB3748B8EBC_XWD_SDI.fw \
    $(PATH_FILES)/etc/firmware/g760L_lensone_fw.img:system/etc/firmware/g760L_lensone_fw.img \
    $(PATH_FILES)/etc/firmware/g760L_ofilm_fw.img:system/etc/firmware/g760L_ofilm_fw.img \
    $(PATH_FILES)/etc/firmware/goodix_fw_g620S.bin:system/etc/firmware/goodix_fw_g620S.bin \
    $(PATH_FILES)/etc/firmware/goodix_new_ofilm_fw.bin:system/etc/firmware/goodix_new_ofilm_fw.bin \
    $(PATH_FILES)/etc/firmware/goodix_ofilm_fw.bin:system/etc/firmware/goodix_ofilm_fw.bin \
    $(PATH_FILES)/etc/firmware/ice40.bin:system/etc/firmware/ice40.bin \
    $(PATH_FILES)/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
    $(PATH_FILES)/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
    $(PATH_FILES)/etc/firmware/nfc_test.bin:system/etc/firmware/nfc_test.bin \
    $(PATH_FILES)/etc/firmware/Signedrompatch_v20.bin:system/etc/firmware/Signedrompatch_v20.bin \
    $(PATH_FILES)/etc/firmware/Signedrompatch_v21.bin:system/etc/firmware/Signedrompatch_v21.bin \
    $(PATH_FILES)/etc/firmware/Signedrompatch_v24.bin:system/etc/firmware/Signedrompatch_v24.bin \
    $(PATH_FILES)/etc/firmware/Signedrompatch_v30.bin:system/etc/firmware/Signedrompatch_v30.bin \
    $(PATH_FILES)/etc/firmware/venus.b00:system/etc/firmware/venus.b00 \
    $(PATH_FILES)/etc/firmware/venus.b01:system/etc/firmware/venus.b01 \
    $(PATH_FILES)/etc/firmware/venus.b02:system/etc/firmware/venus.b02 \
    $(PATH_FILES)/etc/firmware/venus.b03:system/etc/firmware/venus.b03 \
    $(PATH_FILES)/etc/firmware/venus.b04:system/etc/firmware/venus.b04 \
    $(PATH_FILES)/etc/firmware/venus.mbn:system/etc/firmware/venus.mbn \
    $(PATH_FILES)/etc/firmware/venus.mdt:system/etc/firmware/venus.mdt

PRODUCT_COPY_FILES += \
    $(PATH_FILES)/etc/permissions/com.qualcomm.location.vzw_library.xml:system/etc/permissions/com.qualcomm.location.vzw_library.xml \
    $(PATH_FILES)/etc/permissions/com.qualcomm.location.xml:system/etc/permissions/com.qualcomm.location.xml \
    $(PATH_FILES)/etc/permissions/ims.xml:system/etc/permissions/ims.xml \
    $(PATH_FILES)/etc/permissions/qcnvitems.xml:system/etc/permissions/qcnvitems.xml \
    $(PATH_FILES)/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml

PRODUCT_COPY_FILES += \
    $(PATH_FILES)/etc/cacert_location.pem:system/etc/cacert_location.pem \
    $(PATH_FILES)/etc/flp.conf:system/etc/flp.conf \
    $(PATH_FILES)/etc/gps.conf:system/etc/gps.conf \
    $(PATH_FILES)/etc/izat.conf:system/etc/izat.conf \
    $(PATH_FILES)/etc/lowi.conf:system/etc/lowi.conf \
    $(PATH_FILES)/etc/quipc.conf:system/etc/quipc.conf \
    $(PATH_FILES)/etc/sap.conf:system/etc/sap.conf \
    $(PATH_FILES)/etc/xtra_root_cert.pem:system/etc/xtra_root_cert.pem \
    $(PATH_FILES)/etc/xtwifi.conf:system/etc/xtwifi.conf

# Lib
PRODUCT_COPY_FILES += \
    $(PATH_FILES)/lib/drm/libdrmhwomavoneplugin.so:system/lib/drm/libdrmhwomavoneplugin.so

PRODUCT_COPY_FILES += \
    $(PATH_FILES)/lib/hw/gps.default.so:system/lib/hw/gps.msm8916.so \
    $(PATH_FILES)/lib/hw/sensors.msm8916.so:system/lib/hw/sensors.msm8916.so

PRODUCT_COPY_FILES += \
    $(PATH_FILES)/lib/libchromatix_imx135_liveshot.so:system/lib/libchromatix_imx135_liveshot.so \
    $(PATH_FILES)/lib/libcutils.so:system/lib/libcutils.so \
    $(PATH_FILES)/lib/libcutilz.so:system/lib/libcutilz.so \
    $(PATH_FILES)/lib/libdrmdecrypt.so:system/lib/libdrmdecrypt.so \
    $(PATH_FILES)/lib/libgps.utils.so:system/lib/libgps.utils.so \
    $(PATH_FILES)/lib/libhwnv.so:system/lib/libhwnv.so \
    $(PATH_FILES)/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    $(PATH_FILES)/lib/libloc_core.so:system/lib/libloc_core.so \
    $(PATH_FILES)/lib/libloc_ds_api.so:system/lib/libloc_ds_api.so \
    $(PATH_FILES)/lib/libloc_eng.so:system/lib/libloc_eng.so \
    $(PATH_FILES)/lib/libloc_xtra.so:system/lib/libloc_xtra.so \
    $(PATH_FILES)/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
    $(PATH_FILES)/lib/libmmjpeg_interface.so:system/lib/libmmjpeg_interface.so \
    $(PATH_FILES)/lib/libmm-qcamera.so:system/lib/libmm-qcamera.so \
    $(PATH_FILES)/lib/liboeminfo.so:system/lib/liboeminfo.so \
    $(PATH_FILES)/lib/liboeminfo_oem_api.so:system/lib/liboeminfo_oem_api.so \
    $(PATH_FILES)/lib/libqmi_nv_api.so:system/lib/libqmi_nv_api.so \
    $(PATH_FILES)/lib/libqmi_oem_api.so:system/lib/libqmi_oem_api.so \
    $(PATH_FILES)/lib/libqmi_oem_svc.so:system/lib/libqmi_oem_svc.so \
    $(PATH_FILES)/lib/libqomx_core.so:system/lib/libqomx_core.so \
    $(PATH_FILES)/lib/libril.so:system/lib/libril.so \
    $(PATH_FILES)/lib/librmnetctl.so:system/lib/librmnetctl.so \
    $(PATH_FILES)/lib/libtinyxml2.so:system/lib/libtinyxml2.so \
    $(PATH_FILES)/lib/libWVphoneAPI.so:system/lib/libWVphoneAPI.so

# Vendor
PRODUCT_COPY_FILES += \
    $(PATH_FILES)/vendor/bin/audioflacapp:system/vendor/bin/audioflacapp

PRODUCT_COPY_FILES += \
    $(PATH_FILES)/vendor/etc/calmodule.cfg:system/vendor/etc/calmodule.cfg

PRODUCT_COPY_FILES += \
    $(PATH_FILES)/vendor/lib/drm/libdrmprplugin.so:system/vendor/lib/drm/libdrmprplugin.so \
    $(PATH_FILES)/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so

PRODUCT_COPY_FILES += \
    $(PATH_FILES)/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    $(PATH_FILES)/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    $(PATH_FILES)/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    $(PATH_FILES)/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    $(PATH_FILES)/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so

PRODUCT_COPY_FILES += \
    $(PATH_FILES)/vendor/lib/hw/flp.default.so:system/vendor/lib/hw/flp.default.so

PRODUCT_COPY_FILES += \
    $(PATH_FILES)/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so

PRODUCT_COPY_FILES += \
    $(PATH_FILES)/vendor/lib/soundfx/libqcbassboost.so:system/vendor/lib/soundfx/libqcbassboost.so \
    $(PATH_FILES)/vendor/lib/soundfx/libqcreverb.so:system/vendor/lib/soundfx/libqcreverb.so \
    $(PATH_FILES)/vendor/lib/soundfx/libqcvirt.so:system/vendor/lib/soundfx/libqcvirt.so

# Actuator
PRODUCT_COPY_FILES += \
    $(PATH_FILES)/vendor/lib/libactuator_a3907.so:system/vendor/lib/libactuator_a3907.so \
    $(PATH_FILES)/vendor/lib/libactuator_a3907_camcorder.so:system/vendor/lib/libactuator_a3907_camcorder.so \
    $(PATH_FILES)/vendor/lib/libactuator_a3907_camera.so:system/vendor/lib/libactuator_a3907_camera.so \
    $(PATH_FILES)/vendor/lib/libactuator_dw9714.so:system/vendor/lib/libactuator_dw9714.so \
    $(PATH_FILES)/vendor/lib/libactuator_dw9714_13p1ba.so:system/vendor/lib/libactuator_dw9714_13p1ba.so \
    $(PATH_FILES)/vendor/lib/libactuator_dw9714_13p1ba_camcorder.so:system/vendor/lib/libactuator_dw9714_13p1ba_camcorder.so \
    $(PATH_FILES)/vendor/lib/libactuator_dw9714_13p1ba_camera.so:system/vendor/lib/libactuator_dw9714_13p1ba_camera.so \
    $(PATH_FILES)/vendor/lib/libactuator_dw9714_camcorder.so:system/vendor/lib/libactuator_dw9714_camcorder.so \
    $(PATH_FILES)/vendor/lib/libactuator_dw9714_camera.so:system/vendor/lib/libactuator_dw9714_camera.so \
    $(PATH_FILES)/vendor/lib/libactuator_dw9714_q13v04b.so:system/vendor/lib/libactuator_dw9714_q13v04b.so \
    $(PATH_FILES)/vendor/lib/libactuator_dw9714_q13v04b_camcorder.so:system/vendor/lib/libactuator_dw9714_q13v04b_camcorder.so \
    $(PATH_FILES)/vendor/lib/libactuator_dw9714_q13v04b_camera.so:system/vendor/lib/libactuator_dw9714_q13v04b_camera.so \
    $(PATH_FILES)/vendor/lib/libactuator_dw9716.so:system/vendor/lib/libactuator_dw9716.so \
    $(PATH_FILES)/vendor/lib/libactuator_dw9716_camcorder.so:system/vendor/lib/libactuator_dw9716_camcorder.so \
    $(PATH_FILES)/vendor/lib/libactuator_dw9716_camera.so:system/vendor/lib/libactuator_dw9716_camera.so \
    $(PATH_FILES)/vendor/lib/libactuator_imx214_foxconn.so:system/vendor/lib/libactuator_imx214_foxconn.so \
    $(PATH_FILES)/vendor/lib/libactuator_imx214_foxconn_camcorder.so:system/vendor/lib/libactuator_imx214_foxconn_camcorder.so \
    $(PATH_FILES)/vendor/lib/libactuator_imx214_foxconn_camera.so:system/vendor/lib/libactuator_imx214_foxconn_camera.so \
    $(PATH_FILES)/vendor/lib/libactuator_imx214_sunny.so:system/vendor/lib/libactuator_imx214_sunny.so \
    $(PATH_FILES)/vendor/lib/libactuator_imx214_sunny_camcorder.so:system/vendor/lib/libactuator_imx214_sunny_camcorder.so \
    $(PATH_FILES)/vendor/lib/libactuator_imx214_sunny_camera.so:system/vendor/lib/libactuator_imx214_sunny_camera.so \
    $(PATH_FILES)/vendor/lib/libactuator_imx219_liteon.so:system/vendor/lib/libactuator_imx219_liteon.so \
    $(PATH_FILES)/vendor/lib/libactuator_imx219_liteon_camcorder.so:system/vendor/lib/libactuator_imx219_liteon_camcorder.so \
    $(PATH_FILES)/vendor/lib/libactuator_imx219_liteon_camera.so:system/vendor/lib/libactuator_imx219_liteon_camera.so \
    $(PATH_FILES)/vendor/lib/libactuator_imx219_ofilm.so:system/vendor/lib/libactuator_imx219_ofilm.so \
    $(PATH_FILES)/vendor/lib/libactuator_imx219_ofilm_camcorder.so:system/vendor/lib/libactuator_imx219_ofilm_camcorder.so \
    $(PATH_FILES)/vendor/lib/libactuator_imx219_ofilm_camera.so:system/vendor/lib/libactuator_imx219_ofilm_camera.so \
    $(PATH_FILES)/vendor/lib/libactuator_imx328_sunny_p13n10a.so:system/vendor/lib/libactuator_imx328_sunny_p13n10a.so \
    $(PATH_FILES)/vendor/lib/libactuator_imx328_sunny_p13n10a_camcorder.so:system/vendor/lib/libactuator_imx328_sunny_p13n10a_camcorder.so \
    $(PATH_FILES)/vendor/lib/libactuator_imx328_sunny_p13n10a_camera.so:system/vendor/lib/libactuator_imx328_sunny_p13n10a_camera.so \
    $(PATH_FILES)/vendor/lib/libactuator_iu074.so:system/vendor/lib/libactuator_iu074.so \
    $(PATH_FILES)/vendor/lib/libactuator_iu074_camcorder.so:system/vendor/lib/libactuator_iu074_camcorder.so \
    $(PATH_FILES)/vendor/lib/libactuator_iu074_camera.so:system/vendor/lib/libactuator_iu074_camera.so \
    $(PATH_FILES)/vendor/lib/libactuator_ov5648_sunny_p5v18g.so:system/vendor/lib/libactuator_ov5648_sunny_p5v18g.so \
    $(PATH_FILES)/vendor/lib/libactuator_ov5648_sunny_p5v18g_camcorder.so:system/vendor/lib/libactuator_ov5648_sunny_p5v18g_camcorder.so \
    $(PATH_FILES)/vendor/lib/libactuator_ov5648_sunny_p5v18g_camera.so:system/vendor/lib/libactuator_ov5648_sunny_p5v18g_camera.so \
    $(PATH_FILES)/vendor/lib/libactuator_ov8825.so:system/vendor/lib/libactuator_ov8825.so \
    $(PATH_FILES)/vendor/lib/libactuator_ov8825_camcorder.so:system/vendor/lib/libactuator_ov8825_camcorder.so \
    $(PATH_FILES)/vendor/lib/libactuator_ov8825_camera.so:system/vendor/lib/libactuator_ov8825_camera.so \
    $(PATH_FILES)/vendor/lib/libactuator_ov8858_foxconn.so:system/vendor/lib/libactuator_ov8858_foxconn.so \
    $(PATH_FILES)/vendor/lib/libactuator_ov8858_foxconn_camcorder.so:system/vendor/lib/libactuator_ov8858_foxconn_camcorder.so \
    $(PATH_FILES)/vendor/lib/libactuator_ov8858_foxconn_camera.so:system/vendor/lib/libactuator_ov8858_foxconn_camera.so \
    $(PATH_FILES)/vendor/lib/libactuator_ov12830.so:system/vendor/lib/libactuator_ov12830.so \
    $(PATH_FILES)/vendor/lib/libactuator_ov12830_camcorder.so:system/vendor/lib/libactuator_ov12830_camcorder.so \
    $(PATH_FILES)/vendor/lib/libactuator_ov12830_camera.so:system/vendor/lib/libactuator_ov12830_camera.so \
    $(PATH_FILES)/vendor/lib/libactuator_ov13850_sunny_p13v01h.so:system/vendor/lib/libactuator_ov13850_sunny_p13v01h.so \
    $(PATH_FILES)/vendor/lib/libactuator_ov13850_sunny_p13v01h_camcorder.so:system/vendor/lib/libactuator_ov13850_sunny_p13v01h_camcorder.so \
    $(PATH_FILES)/vendor/lib/libactuator_ov13850_sunny_p13v01h_camera.so:system/vendor/lib/libactuator_ov13850_sunny_p13v01h_camera.so \
    $(PATH_FILES)/vendor/lib/libactuator_rohm_bu64243gwz.so:system/vendor/lib/libactuator_rohm_bu64243gwz.so \
    $(PATH_FILES)/vendor/lib/libactuator_rohm_bu64243gwz_camcorder.so:system/vendor/lib/libactuator_rohm_bu64243gwz_camcorder.so \
    $(PATH_FILES)/vendor/lib/libactuator_rohm_bu64243gwz_camera.so:system/vendor/lib/libactuator_rohm_bu64243gwz_camera.so \
    $(PATH_FILES)/vendor/lib/libactuator_s5k4e1_liteon_13p1.so:system/vendor/lib/libactuator_s5k4e1_liteon_13p1.so \
    $(PATH_FILES)/vendor/lib/libactuator_s5k4e1_liteon_13p1_camcorder.so:system/vendor/lib/libactuator_s5k4e1_liteon_13p1_camcorder.so \
    $(PATH_FILES)/vendor/lib/libactuator_s5k4e1_liteon_13p1_camera.so:system/vendor/lib/libactuator_s5k4e1_liteon_13p1_camera.so

# Chromatix
PRODUCT_COPY_FILES += \
    $(PATH_FILES)/vendor/lib/libchromatix_gc2355_ofilm_ohw2f03_common.so:system/vendor/lib/libchromatix_gc2355_ofilm_ohw2f03_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_gc2355_ofilm_ohw2f03_default_video.so:system/vendor/lib/libchromatix_gc2355_ofilm_ohw2f03_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_gc2355_ofilm_ohw2f03_preview.so:system/vendor/lib/libchromatix_gc2355_ofilm_ohw2f03_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx132_common.so:system/vendor/lib/libchromatix_imx132_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx132_default_video.so:system/vendor/lib/libchromatix_imx132_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx132_liveshot.so:system/vendor/lib/libchromatix_imx132_liveshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx132_preview.so:system/vendor/lib/libchromatix_imx132_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx132_snapshot.so:system/vendor/lib/libchromatix_imx132_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx132_snapshot.so:system/vendor/lib/libchromatix_imx132_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx134_common.so:system/vendor/lib/libchromatix_imx134_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx134_default_video.so:system/vendor/lib/libchromatix_imx134_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx134_hfr_60.so:system/vendor/lib/libchromatix_imx134_hfr_60.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx134_hfr_120.so:system/vendor/lib/libchromatix_imx134_hfr_120.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx134_preview.so:system/vendor/lib/libchromatix_imx134_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx134_snapshot.so:system/vendor/lib/libchromatix_imx134_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx135_common.so:system/vendor/lib/libchromatix_imx135_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx135_default_video.so:system/vendor/lib/libchromatix_imx135_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx135_hfr_60.so:system/vendor/lib/libchromatix_imx135_hfr_60.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx135_hfr_90.so:system/vendor/lib/libchromatix_imx135_hfr_90.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx135_hfr_120.so:system/vendor/lib/libchromatix_imx135_hfr_120.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx135_preview.so:system/vendor/lib/libchromatix_imx135_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx135_snapshot.so:system/vendor/lib/libchromatix_imx135_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx135_video_hd.so:system/vendor/lib/libchromatix_imx135_video_hd.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx214_foxconn_10m30fps.so:system/vendor/lib/libchromatix_imx214_foxconn_10m30fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx214_foxconn_10m_zsl_preview.so:system/vendor/lib/libchromatix_imx214_foxconn_10m_zsl_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx214_foxconn_13m_zsl_preview.so:system/vendor/lib/libchromatix_imx214_foxconn_13m_zsl_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx214_foxconn_common.so:system/vendor/lib/libchromatix_imx214_foxconn_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx214_foxconn_hfr_60fps.so:system/vendor/lib/libchromatix_imx214_foxconn_hfr_60fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx214_foxconn_preview.so:system/vendor/lib/libchromatix_imx214_foxconn_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx214_foxconn_video.so:system/vendor/lib/libchromatix_imx214_foxconn_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx214_sunny_10m30fps.so:system/vendor/lib/libchromatix_imx214_sunny_10m30fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx214_sunny_10m_zsl_preview.so:system/vendor/lib/libchromatix_imx214_sunny_10m_zsl_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx214_sunny_13m_zsl_preview.so:system/vendor/lib/libchromatix_imx214_sunny_13m_zsl_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx214_sunny_common.so:system/vendor/lib/libchromatix_imx214_sunny_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx214_sunny_hfr_60fps.so:system/vendor/lib/libchromatix_imx214_sunny_hfr_60fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx214_sunny_preview.so:system/vendor/lib/libchromatix_imx214_sunny_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx214_sunny_video.so:system/vendor/lib/libchromatix_imx214_sunny_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx219_liteon_common.so:system/vendor/lib/libchromatix_imx219_liteon_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx219_liteon_preview.so:system/vendor/lib/libchromatix_imx219_liteon_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx219_liteon_video.so:system/vendor/lib/libchromatix_imx219_liteon_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx219_liteon_zsl_preview.so:system/vendor/lib/libchromatix_imx219_liteon_zsl_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx219_ofilm_common.so:system/vendor/lib/libchromatix_imx219_ofilm_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx219_ofilm_preview.so:system/vendor/lib/libchromatix_imx219_ofilm_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx219_ofilm_video.so:system/vendor/lib/libchromatix_imx219_ofilm_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx219_ofilm_zsl_preview.so:system/vendor/lib/libchromatix_imx219_ofilm_zsl_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx328_sunny_p13n10a_common.so:system/vendor/lib/libchromatix_imx328_sunny_p13n10a_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx328_sunny_p13n10a_default_video.so:system/vendor/lib/libchromatix_imx328_sunny_p13n10a_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx328_sunny_p13n10a_preview.so:system/vendor/lib/libchromatix_imx328_sunny_p13n10a_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_imx328_sunny_p13n10a_snapshot.so:system/vendor/lib/libchromatix_imx328_sunny_p13n10a_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_mt9d015_sunny_p2m19a_common.so:system/vendor/lib/libchromatix_mt9d015_sunny_p2m19a_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_mt9d015_sunny_p2m19a_default_video.so:system/vendor/lib/libchromatix_mt9d015_sunny_p2m19a_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_mt9d015_sunny_p2m19a_g620s_common.so:system/vendor/lib/libchromatix_mt9d015_sunny_p2m19a_g620s_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_mt9d015_sunny_p2m19a_g620s_default_video.so:system/vendor/lib/libchromatix_mt9d015_sunny_p2m19a_g620s_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_mt9d015_sunny_p2m19a_g620s_preview.so:system/vendor/lib/libchromatix_mt9d015_sunny_p2m19a_g620s_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_mt9d015_sunny_p2m19a_g620s_snapshot.so:system/vendor/lib/libchromatix_mt9d015_sunny_p2m19a_g620s_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_mt9d015_sunny_p2m19a_preview.so:system/vendor/lib/libchromatix_mt9d015_sunny_p2m19a_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_mt9d015_sunny_p2m19a_snapshot.so:system/vendor/lib/libchromatix_mt9d015_sunny_p2m19a_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_mt9d015_sunny_p2m19a_y550_common.so:system/vendor/lib/libchromatix_mt9d015_sunny_p2m19a_y550_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_mt9d015_sunny_p2m19a_y550_default_video.so:system/vendor/lib/libchromatix_mt9d015_sunny_p2m19a_y550_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_mt9d015_sunny_p2m19a_y550_preview.so:system/vendor/lib/libchromatix_mt9d015_sunny_p2m19a_y550_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_mt9d015_sunny_p2m19a_y550_snapshot.so:system/vendor/lib/libchromatix_mt9d015_sunny_p2m19a_y550_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov2680_5987fhq_common.so:system/vendor/lib/libchromatix_ov2680_5987fhq_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov2680_5987fhq_default_video.so:system/vendor/lib/libchromatix_ov2680_5987fhq_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov2680_5987fhq_preview.so:system/vendor/lib/libchromatix_ov2680_5987fhq_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov2680_5987fhq_snapshot.so:system/vendor/lib/libchromatix_ov2680_5987fhq_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov2680_byd_bm2920b_common.so:system/vendor/lib/libchromatix_ov2680_byd_bm2920b_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov2680_byd_bm2920b_default_video.so:system/vendor/lib/libchromatix_ov2680_byd_bm2920b_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov2680_byd_bm2920b_preview.so:system/vendor/lib/libchromatix_ov2680_byd_bm2920b_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov2680_byd_bm2920b_snapshot.so:system/vendor/lib/libchromatix_ov2680_byd_bm2920b_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov2680_common.so:system/vendor/lib/libchromatix_ov2680_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov2680_default_video.so:system/vendor/lib/libchromatix_ov2680_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov2680_ofilm_fe16_common.so:system/vendor/lib/libchromatix_ov2680_ofilm_fe16_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov2680_ofilm_fe16_default_video.so:system/vendor/lib/libchromatix_ov2680_ofilm_fe16_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov2680_ofilm_fe16_g620s_common.so:system/vendor/lib/libchromatix_ov2680_ofilm_fe16_g620s_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov2680_ofilm_fe16_g620s_default_video.so:system/vendor/lib/libchromatix_ov2680_ofilm_fe16_g620s_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov2680_ofilm_fe16_g620s_preview.so:system/vendor/lib/libchromatix_ov2680_ofilm_fe16_g620s_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov2680_ofilm_fe16_g620s_snapshot.so:system/vendor/lib/libchromatix_ov2680_ofilm_fe16_g620s_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov2680_ofilm_fe16_preview.so:system/vendor/lib/libchromatix_ov2680_ofilm_fe16_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov2680_ofilm_fe16_snapshot.so:system/vendor/lib/libchromatix_ov2680_ofilm_fe16_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov2680_ofilm_fe16_y550_common.so:system/vendor/lib/libchromatix_ov2680_ofilm_fe16_y550_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov2680_ofilm_fe16_y550_default_video.so:system/vendor/lib/libchromatix_ov2680_ofilm_fe16_y550_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov2680_ofilm_fe16_y550_preview.so:system/vendor/lib/libchromatix_ov2680_ofilm_fe16_y550_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov2680_ofilm_fe16_y550_snapshot.so:system/vendor/lib/libchromatix_ov2680_ofilm_fe16_y550_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov2680_preview.so:system/vendor/lib/libchromatix_ov2680_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov2680_snapshot.so:system/vendor/lib/libchromatix_ov2680_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov2720_common.so:system/vendor/lib/libchromatix_ov2720_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov2720_default_video.so:system/vendor/lib/libchromatix_ov2720_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov2720_hfr.so:system/vendor/lib/libchromatix_ov2720_hfr.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov2720_liveshot.so:system/vendor/lib/libchromatix_ov2720_liveshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov2720_preview.so:system/vendor/lib/libchromatix_ov2720_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov2720_zsl.so:system/vendor/lib/libchromatix_ov2720_zsl.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_foxconn_132_common.so:system/vendor/lib/libchromatix_ov5648_foxconn_132_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_foxconn_132_default_video.so:system/vendor/lib/libchromatix_ov5648_foxconn_132_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_foxconn_132_preview.so:system/vendor/lib/libchromatix_ov5648_foxconn_132_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_foxconn_132_snapshot.so:system/vendor/lib/libchromatix_ov5648_foxconn_132_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_foxconn_cherry_common.so:system/vendor/lib/libchromatix_ov5648_foxconn_cherry_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_foxconn_cherry_default_video.so:system/vendor/lib/libchromatix_ov5648_foxconn_cherry_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_foxconn_cherry_preview.so:system/vendor/lib/libchromatix_ov5648_foxconn_cherry_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_foxconn_cherry_snapshot.so:system/vendor/lib/libchromatix_ov5648_foxconn_cherry_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_foxconn_common.so:system/vendor/lib/libchromatix_ov5648_foxconn_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_foxconn_default_video.so:system/vendor/lib/libchromatix_ov5648_foxconn_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_foxconn_g760_common.so:system/vendor/lib/libchromatix_ov5648_foxconn_g760_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_foxconn_g760_default_video.so:system/vendor/lib/libchromatix_ov5648_foxconn_g760_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_foxconn_g760_preview.so:system/vendor/lib/libchromatix_ov5648_foxconn_g760_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_foxconn_g760_snapshot.so:system/vendor/lib/libchromatix_ov5648_foxconn_g760_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_foxconn_preview.so:system/vendor/lib/libchromatix_ov5648_foxconn_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_foxconn_snapshot.so:system/vendor/lib/libchromatix_ov5648_foxconn_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_oty5f03_common.so:system/vendor/lib/libchromatix_ov5648_oty5f03_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_oty5f03_default_video.so:system/vendor/lib/libchromatix_ov5648_oty5f03_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_oty5f03_preview.so:system/vendor/lib/libchromatix_ov5648_oty5f03_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_oty5f03_snapshot.so:system/vendor/lib/libchromatix_ov5648_oty5f03_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_oty5f03_zsl.so:system/vendor/lib/libchromatix_ov5648_oty5f03_zsl.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_p5v18g_common.so:system/vendor/lib/libchromatix_ov5648_p5v18g_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_p5v18g_default_video.so:system/vendor/lib/libchromatix_ov5648_p5v18g_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_p5v18g_default_video_hd.so:system/vendor/lib/libchromatix_ov5648_p5v18g_default_video_hd.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_p5v18g_preview.so:system/vendor/lib/libchromatix_ov5648_p5v18g_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_p5v18g_snapshot.so:system/vendor/lib/libchromatix_ov5648_p5v18g_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_p5v18g_zsl.so:system/vendor/lib/libchromatix_ov5648_p5v18g_zsl.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_q5v22e_common.so:system/vendor/lib/libchromatix_ov5648_q5v22e_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_q5v22e_default_video.so:system/vendor/lib/libchromatix_ov5648_q5v22e_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_q5v22e_default_video_hd.so:system/vendor/lib/libchromatix_ov5648_q5v22e_default_video_hd.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_q5v22e_preview.so:system/vendor/lib/libchromatix_ov5648_q5v22e_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_q5v22e_snapshot.so:system/vendor/lib/libchromatix_ov5648_q5v22e_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_q5v22e_zsl.so:system/vendor/lib/libchromatix_ov5648_q5v22e_zsl.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_sunny_p5v18g_common.so:system/vendor/lib/libchromatix_ov5648_sunny_p5v18g_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_sunny_p5v18g_default_video.so:system/vendor/lib/libchromatix_ov5648_sunny_p5v18g_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_sunny_p5v18g_default_video_hd.so:system/vendor/lib/libchromatix_ov5648_sunny_p5v18g_default_video_hd.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_sunny_p5v18g_preview.so:system/vendor/lib/libchromatix_ov5648_sunny_p5v18g_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_sunny_p5v18g_snapshot.so:system/vendor/lib/libchromatix_ov5648_sunny_p5v18g_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_sunny_p5v18g_zsl.so:system/vendor/lib/libchromatix_ov5648_sunny_p5v18g_zsl.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_sunny_p5v36d_common.so:system/vendor/lib/libchromatix_ov5648_sunny_p5v36d_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_sunny_p5v36d_default_video.so:system/vendor/lib/libchromatix_ov5648_sunny_p5v36d_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_sunny_p5v36d_default_video_hd.so:system/vendor/lib/libchromatix_ov5648_sunny_p5v36d_default_video_hd.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_sunny_p5v36d_preview.so:system/vendor/lib/libchromatix_ov5648_sunny_p5v36d_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_sunny_p5v36d_snapshot.so:system/vendor/lib/libchromatix_ov5648_sunny_p5v36d_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5648_sunny_p5v36d_zsl.so:system/vendor/lib/libchromatix_ov5648_sunny_p5v36d_zsl.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_byd_cht854b_common.so:system/vendor/lib/libchromatix_ov5670_byd_cht854b_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_byd_cht854b_default_video.so:system/vendor/lib/libchromatix_ov5670_byd_cht854b_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_byd_cht854b_hfr_60fps.so:system/vendor/lib/libchromatix_ov5670_byd_cht854b_hfr_60fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_byd_cht854b_hfr_90fps.so:system/vendor/lib/libchromatix_ov5670_byd_cht854b_hfr_90fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_byd_cht854b_hfr_120fps.so:system/vendor/lib/libchromatix_ov5670_byd_cht854b_hfr_120fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_byd_cht854b_liveshot.so:system/vendor/lib/libchromatix_ov5670_byd_cht854b_liveshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_byd_cht854b_preview.so:system/vendor/lib/libchromatix_ov5670_byd_cht854b_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_byd_cht854b_snapshot.so:system/vendor/lib/libchromatix_ov5670_byd_cht854b_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_byd_cht854b_video_hd.so:system/vendor/lib/libchromatix_ov5670_byd_cht854b_video_hd.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_byd_cht854b_zsl.so:system/vendor/lib/libchromatix_ov5670_byd_cht854b_zsl.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_q5v41b_common.so:system/vendor/lib/libchromatix_ov5670_q5v41b_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_q5v41b_default_video.so:system/vendor/lib/libchromatix_ov5670_q5v41b_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_q5v41b_hfr_60fps.so:system/vendor/lib/libchromatix_ov5670_q5v41b_hfr_60fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_q5v41b_hfr_90fps.so:system/vendor/lib/libchromatix_ov5670_q5v41b_hfr_90fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_q5v41b_hfr_120fps.so:system/vendor/lib/libchromatix_ov5670_q5v41b_hfr_120fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_q5v41b_liveshot.so:system/vendor/lib/libchromatix_ov5670_q5v41b_liveshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_q5v41b_preview.so:system/vendor/lib/libchromatix_ov5670_q5v41b_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_q5v41b_snapshot.so:system/vendor/lib/libchromatix_ov5670_q5v41b_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_q5v41b_video_hd.so:system/vendor/lib/libchromatix_ov5670_q5v41b_video_hd.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_q5v41b_zsl.so:system/vendor/lib/libchromatix_ov5670_q5v41b_zsl.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_sunny_p5v42b_common.so:system/vendor/lib/libchromatix_ov5670_sunny_p5v42b_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_sunny_p5v42b_default_video.so:system/vendor/lib/libchromatix_ov5670_sunny_p5v42b_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_sunny_p5v42b_hfr_60fps.so:system/vendor/lib/libchromatix_ov5670_sunny_p5v42b_hfr_60fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_sunny_p5v42b_hfr_90fps.so:system/vendor/lib/libchromatix_ov5670_sunny_p5v42b_hfr_90fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_sunny_p5v42b_hfr_120fps.so:system/vendor/lib/libchromatix_ov5670_sunny_p5v42b_hfr_120fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_sunny_p5v42b_liveshot.so:system/vendor/lib/libchromatix_ov5670_sunny_p5v42b_liveshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_sunny_p5v42b_preview.so:system/vendor/lib/libchromatix_ov5670_sunny_p5v42b_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_sunny_p5v42b_snapshot.so:system/vendor/lib/libchromatix_ov5670_sunny_p5v42b_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_sunny_p5v42b_video_hd.so:system/vendor/lib/libchromatix_ov5670_sunny_p5v42b_video_hd.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov5670_sunny_p5v42b_zsl.so:system/vendor/lib/libchromatix_ov5670_sunny_p5v42b_zsl.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8825_common.so:system/vendor/lib/libchromatix_ov8825_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8825_default_video.so:system/vendor/lib/libchromatix_ov8825_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8825_hfr_60fps.so:system/vendor/lib/libchromatix_ov8825_hfr_60fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8825_hfr_90fps.so:system/vendor/lib/libchromatix_ov8825_hfr_90fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8825_hfr_120fps.so:system/vendor/lib/libchromatix_ov8825_hfr_120fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8825_liveshot.so:system/vendor/lib/libchromatix_ov8825_liveshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8825_liveshot_hd.so:system/vendor/lib/libchromatix_ov8825_liveshot_hd.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8825_preview.so:system/vendor/lib/libchromatix_ov8825_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8825_preview_hd.so:system/vendor/lib/libchromatix_ov8825_preview_hd.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8825_snapshot.so:system/vendor/lib/libchromatix_ov8825_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8825_snapshot_hd.so:system/vendor/lib/libchromatix_ov8825_snapshot_hd.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8825_video_hd.so:system/vendor/lib/libchromatix_ov8825_video_hd.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8825_zsl.so:system/vendor/lib/libchromatix_ov8825_zsl.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8858_foxconn_common.so:system/vendor/lib/libchromatix_ov8858_foxconn_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8858_foxconn_default_video.so:system/vendor/lib/libchromatix_ov8858_foxconn_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8858_foxconn_preview.so:system/vendor/lib/libchromatix_ov8858_foxconn_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8858_foxconn_snapshot.so:system/vendor/lib/libchromatix_ov8858_foxconn_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8865_q8v18a_common.so:system/vendor/lib/libchromatix_ov8865_q8v18a_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8865_q8v18a_default_video.so:system/vendor/lib/libchromatix_ov8865_q8v18a_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8865_q8v18a_hfr_60fps.so:system/vendor/lib/libchromatix_ov8865_q8v18a_hfr_60fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8865_q8v18a_hfr_90fps.so:system/vendor/lib/libchromatix_ov8865_q8v18a_hfr_90fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8865_q8v18a_hfr_120fps.so:system/vendor/lib/libchromatix_ov8865_q8v18a_hfr_120fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8865_q8v18a_liveshot.so:system/vendor/lib/libchromatix_ov8865_q8v18a_liveshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8865_q8v18a_preview.so:system/vendor/lib/libchromatix_ov8865_q8v18a_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8865_q8v18a_snapshot.so:system/vendor/lib/libchromatix_ov8865_q8v18a_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8865_q8v18a_video_hd.so:system/vendor/lib/libchromatix_ov8865_q8v18a_video_hd.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov8865_q8v18a_zsl.so:system/vendor/lib/libchromatix_ov8865_q8v18a_zsl.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov9724_common.so:system/vendor/lib/libchromatix_ov9724_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov9724_default_video.so:system/vendor/lib/libchromatix_ov9724_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov9724_foxconn_common.so:system/vendor/lib/libchromatix_ov9724_foxconn_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov9724_foxconn_default_video.so:system/vendor/lib/libchromatix_ov9724_foxconn_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov9724_foxconn_preview.so:system/vendor/lib/libchromatix_ov9724_foxconn_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov9724_liveshot.so:system/vendor/lib/libchromatix_ov9724_liveshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov9724_preview.so:system/vendor/lib/libchromatix_ov9724_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov13850_common.so:system/vendor/lib/libchromatix_ov13850_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov13850_default_video.so:system/vendor/lib/libchromatix_ov13850_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov13850_hfr_60fps.so:system/vendor/lib/libchromatix_ov13850_hfr_60fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov13850_hfr_90fps.so:system/vendor/lib/libchromatix_ov13850_hfr_90fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov13850_hfr_120fps.so:system/vendor/lib/libchromatix_ov13850_hfr_120fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov13850_preview.so:system/vendor/lib/libchromatix_ov13850_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov13850_snapshot.so:system/vendor/lib/libchromatix_ov13850_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov13850_sunny_p13v01h_common.so:system/vendor/lib/libchromatix_ov13850_sunny_p13v01h_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov13850_sunny_p13v01h_default_video.so:system/vendor/lib/libchromatix_ov13850_sunny_p13v01h_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov13850_sunny_p13v01h_preview.so:system/vendor/lib/libchromatix_ov13850_sunny_p13v01h_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_ov13850_sunny_p13v01h_snapshot.so:system/vendor/lib/libchromatix_ov13850_sunny_p13v01h_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k3l1yx_common.so:system/vendor/lib/libchromatix_s5k3l1yx_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k3l1yx_default_video.so:system/vendor/lib/libchromatix_s5k3l1yx_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k3l1yx_hfr_60fps.so:system/vendor/lib/libchromatix_s5k3l1yx_hfr_60fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k3l1yx_hfr_90fps.so:system/vendor/lib/libchromatix_s5k3l1yx_hfr_90fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k3l1yx_hfr_120fps.so:system/vendor/lib/libchromatix_s5k3l1yx_hfr_120fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k3l1yx_liveshot.so:system/vendor/lib/libchromatix_s5k3l1yx_liveshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k3l1yx_preview.so:system/vendor/lib/libchromatix_s5k3l1yx_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k3l1yx_snapshot.so:system/vendor/lib/libchromatix_s5k3l1yx_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k3l1yx_video_hd.so:system/vendor/lib/libchromatix_s5k3l1yx_video_hd.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k3l1yx_zsl.so:system/vendor/lib/libchromatix_s5k3l1yx_zsl.so \
    $(PATH_FILES)/vendor/lib/libchromatix_S5K4E1_13P1BA_common.so:system/vendor/lib/libchromatix_S5K4E1_13P1BA_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_S5K4E1_13P1BA_default_video.so:system/vendor/lib/libchromatix_S5K4E1_13P1BA_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_S5K4E1_13P1BA_hfr_60fps.so:system/vendor/lib/libchromatix_S5K4E1_13P1BA_hfr_60fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_S5K4E1_13P1BA_hfr_90fps.so:system/vendor/lib/libchromatix_S5K4E1_13P1BA_hfr_90fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_S5K4E1_13P1BA_hfr_120fps.so:system/vendor/lib/libchromatix_S5K4E1_13P1BA_hfr_120fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_S5K4E1_13P1BA_liveshot.so:system/vendor/lib/libchromatix_S5K4E1_13P1BA_liveshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_S5K4E1_13P1BA_preview.so:system/vendor/lib/libchromatix_S5K4E1_13P1BA_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_S5K4E1_13P1BA_snapshot.so:system/vendor/lib/libchromatix_S5K4E1_13P1BA_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_S5K4E1_13P1BA_video_hd.so:system/vendor/lib/libchromatix_S5K4E1_13P1BA_video_hd.so \
    $(PATH_FILES)/vendor/lib/libchromatix_S5K4E1_13P1BA_zsl.so:system/vendor/lib/libchromatix_S5K4E1_13P1BA_zsl.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k4e1_foxconn_dc0301a_common.so:system/vendor/lib/libchromatix_s5k4e1_foxconn_dc0301a_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k4e1_foxconn_dc0301a_default_video.so:system/vendor/lib/libchromatix_s5k4e1_foxconn_dc0301a_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k4e1_foxconn_dc0301a_hfr_60fps.so:system/vendor/lib/libchromatix_s5k4e1_foxconn_dc0301a_hfr_60fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k4e1_foxconn_dc0301a_hfr_90fps.so:system/vendor/lib/libchromatix_s5k4e1_foxconn_dc0301a_hfr_90fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k4e1_foxconn_dc0301a_hfr_120fps.so:system/vendor/lib/libchromatix_s5k4e1_foxconn_dc0301a_hfr_120fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k4e1_foxconn_dc0301a_liveshot.so:system/vendor/lib/libchromatix_s5k4e1_foxconn_dc0301a_liveshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k4e1_foxconn_dc0301a_preview.so:system/vendor/lib/libchromatix_s5k4e1_foxconn_dc0301a_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k4e1_foxconn_dc0301a_snapshot.so:system/vendor/lib/libchromatix_s5k4e1_foxconn_dc0301a_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k4e1_foxconn_dc0301a_video_hd.so:system/vendor/lib/libchromatix_s5k4e1_foxconn_dc0301a_video_hd.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k4e1_foxconn_dc0301a_zsl.so:system/vendor/lib/libchromatix_s5k4e1_foxconn_dc0301a_zsl.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k4e1_liteon_13p1_common.so:system/vendor/lib/libchromatix_s5k4e1_liteon_13p1_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k4e1_liteon_13p1_default_video.so:system/vendor/lib/libchromatix_s5k4e1_liteon_13p1_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k4e1_liteon_13p1_hfr_60fps.so:system/vendor/lib/libchromatix_s5k4e1_liteon_13p1_hfr_60fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k4e1_liteon_13p1_hfr_90fps.so:system/vendor/lib/libchromatix_s5k4e1_liteon_13p1_hfr_90fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k4e1_liteon_13p1_hfr_120fps.so:system/vendor/lib/libchromatix_s5k4e1_liteon_13p1_hfr_120fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k4e1_liteon_13p1_liveshot.so:system/vendor/lib/libchromatix_s5k4e1_liteon_13p1_liveshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k4e1_liteon_13p1_preview.so:system/vendor/lib/libchromatix_s5k4e1_liteon_13p1_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k4e1_liteon_13p1_snapshot.so:system/vendor/lib/libchromatix_s5k4e1_liteon_13p1_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k4e1_liteon_13p1_video_hd.so:system/vendor/lib/libchromatix_s5k4e1_liteon_13p1_video_hd.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k4e1_liteon_13p1_zsl.so:system/vendor/lib/libchromatix_s5k4e1_liteon_13p1_zsl.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k4e1_sunny_132_common.so:system/vendor/lib/libchromatix_s5k4e1_sunny_132_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k4e1_sunny_132_default_video.so:system/vendor/lib/libchromatix_s5k4e1_sunny_132_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k4e1_sunny_132_preview.so:system/vendor/lib/libchromatix_s5k4e1_sunny_132_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k4e1_sunny_132_snapshot.so:system/vendor/lib/libchromatix_s5k4e1_sunny_132_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k4e1_sunny_cherry_common.so:system/vendor/lib/libchromatix_s5k4e1_sunny_cherry_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k4e1_sunny_cherry_default_video.so:system/vendor/lib/libchromatix_s5k4e1_sunny_cherry_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k4e1_sunny_cherry_preview.so:system/vendor/lib/libchromatix_s5k4e1_sunny_cherry_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k4e1_sunny_cherry_snapshot.so:system/vendor/lib/libchromatix_s5k4e1_sunny_cherry_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k4e1_sunny_common.so:system/vendor/lib/libchromatix_s5k4e1_sunny_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k4e1_sunny_default_video.so:system/vendor/lib/libchromatix_s5k4e1_sunny_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k4e1_sunny_g760_common.so:system/vendor/lib/libchromatix_s5k4e1_sunny_g760_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k4e1_sunny_g760_default_video.so:system/vendor/lib/libchromatix_s5k4e1_sunny_g760_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k4e1_sunny_g760_preview.so:system/vendor/lib/libchromatix_s5k4e1_sunny_g760_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k4e1_sunny_g760_snapshot.so:system/vendor/lib/libchromatix_s5k4e1_sunny_g760_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k4e1_sunny_preview.so:system/vendor/lib/libchromatix_s5k4e1_sunny_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k4e1_sunny_snapshot.so:system/vendor/lib/libchromatix_s5k4e1_sunny_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k9a1_liteon_common.so:system/vendor/lib/libchromatix_s5k9a1_liteon_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k9a1_liteon_default_video.so:system/vendor/lib/libchromatix_s5k9a1_liteon_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k9a1_liteon_liveshot.so:system/vendor/lib/libchromatix_s5k9a1_liteon_liveshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_s5k9a1_liteon_preview.so:system/vendor/lib/libchromatix_s5k9a1_liteon_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_SKUAA_ST_gc0339_common.so:system/vendor/lib/libchromatix_SKUAA_ST_gc0339_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_SKUAA_ST_gc0339_default_video.so:system/vendor/lib/libchromatix_SKUAA_ST_gc0339_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_SKUAA_ST_gc0339_preview.so:system/vendor/lib/libchromatix_SKUAA_ST_gc0339_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_skuab_shinetech_gc0339_common.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_skuab_shinetech_gc0339_default_video.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_skuab_shinetech_gc0339_liveshot.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_liveshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_skuab_shinetech_gc0339_preview.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_skuab_shinetech_gc0339_snapshot.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_skuab_shinetech_gc0339_zsl.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_zsl.so \
    $(PATH_FILES)/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_common.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_default_video.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_60fps.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_60fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_90fps.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_90fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_120fps.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_120fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_liveshot.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_liveshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_preview.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_snapshot.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_video_hd.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_video_hd.so \
    $(PATH_FILES)/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_zsl.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_zsl.so \
    $(PATH_FILES)/vendor/lib/libchromatix_skuf_ov5648_p5v23c_common.so:system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_skuf_ov5648_p5v23c_default_video.so:system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_skuf_ov5648_p5v23c_preview.so:system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_skuf_ov5648_p5v23c_snapshot.so:system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_skuf_ov12830_p12v01c_common.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_common.so \
    $(PATH_FILES)/vendor/lib/libchromatix_skuf_ov12830_p12v01c_default_video.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_default_video.so \
    $(PATH_FILES)/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_60fps.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_60fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_90fps.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_90fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_120fps.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_120fps.so \
    $(PATH_FILES)/vendor/lib/libchromatix_skuf_ov12830_p12v01c_preview.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_preview.so \
    $(PATH_FILES)/vendor/lib/libchromatix_skuf_ov12830_p12v01c_snapshot.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_snapshot.so \
    $(PATH_FILES)/vendor/lib/libchromatix_skuf_ov12830_p12v01c_video_hd.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_video_hd.so \
    $(PATH_FILES)/vendor/lib/libchromatix_skuf_ov12830_p12v01c_zsl.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_zsl.so

# Mmcamera
PRODUCT_COPY_FILES += \
    $(PATH_FILES)/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
    $(PATH_FILES)/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
    $(PATH_FILES)/vendor/lib/libmmcamera2_frame_algorithm.so:system/vendor/lib/libmmcamera2_frame_algorithm.so \
    $(PATH_FILES)/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    $(PATH_FILES)/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    $(PATH_FILES)/vendor/lib/libmmcamera2_is.so:system/vendor/lib/libmmcamera2_is.so \
    $(PATH_FILES)/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    $(PATH_FILES)/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
    $(PATH_FILES)/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    $(PATH_FILES)/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
    $(PATH_FILES)/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    $(PATH_FILES)/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
    $(PATH_FILES)/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_gc2355_ofilm_ohw2f03.so:system/vendor/lib/libmmcamera_gc2355_ofilm_ohw2f03.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_hdr_lib.so:system/vendor/lib/libmmcamera_hdr_lib.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_hi256.so:system/vendor/lib/libmmcamera_hi256.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_imx132.so:system/vendor/lib/libmmcamera_imx132.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_imx134.so:system/vendor/lib/libmmcamera_imx134.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_imx135.so:system/vendor/lib/libmmcamera_imx135.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_imx214_foxconn.so:system/vendor/lib/libmmcamera_imx214_foxconn.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_imx214_sunny.so:system/vendor/lib/libmmcamera_imx214_sunny.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_imx219_liteon.so:system/vendor/lib/libmmcamera_imx219_liteon.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_imx219_ofilm.so:system/vendor/lib/libmmcamera_imx219_ofilm.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_imx328_sunny_p13n10a.so:system/vendor/lib/libmmcamera_imx328_sunny_p13n10a.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_liteon_imx219_eeprom.so:system/vendor/lib/libmmcamera_liteon_imx219_eeprom.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_mt9d015_sunny_p2m19a.so:system/vendor/lib/libmmcamera_mt9d015_sunny_p2m19a.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_mt9m114.so:system/vendor/lib/libmmcamera_mt9m114.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_ofilm_oty5f03_eeprom.so:system/vendor/lib/libmmcamera_ofilm_oty5f03_eeprom.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_ov2680.so:system/vendor/lib/libmmcamera_ov2680.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_ov2680_5987fhq.so:system/vendor/lib/libmmcamera_ov2680_5987fhq.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_ov2680_byd_bm2920b.so:system/vendor/lib/libmmcamera_ov2680_byd_bm2920b.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_ov2680_ofilm_fe16.so:system/vendor/lib/libmmcamera_ov2680_ofilm_fe16.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_ov2680_skuhf.so:system/vendor/lib/libmmcamera_ov2680_skuhf.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_ov2720.so:system/vendor/lib/libmmcamera_ov2720.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_ov5645.so:system/vendor/lib/libmmcamera_ov5645.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_ov5648_foxconn.so:system/vendor/lib/libmmcamera_ov5648_foxconn.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_ov5648_foxconn_132.so:system/vendor/lib/libmmcamera_ov5648_foxconn_132.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_ov5648_oty5f03.so:system/vendor/lib/libmmcamera_ov5648_oty5f03.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_ov5648_p5v18g.so:system/vendor/lib/libmmcamera_ov5648_p5v18g.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_ov5648_q5v22e.so:system/vendor/lib/libmmcamera_ov5648_q5v22e.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_ov5648_sunny_p5v18g.so:system/vendor/lib/libmmcamera_ov5648_sunny_p5v18g.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_ov5648_sunny_p5v36d.so:system/vendor/lib/libmmcamera_ov5648_sunny_p5v36d.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_ov5670_byd_cht854b.so:system/vendor/lib/libmmcamera_ov5670_byd_cht854b.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_ov5670_q5v41b.so:system/vendor/lib/libmmcamera_ov5670_q5v41b.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_ov5670_sunny_p5v42b.so:system/vendor/lib/libmmcamera_ov5670_sunny_p5v42b.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_ov8825.so:system/vendor/lib/libmmcamera_ov8825.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_ov8858_foxconn.so:system/vendor/lib/libmmcamera_ov8858_foxconn.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_ov8865_q8v18a.so:system/vendor/lib/libmmcamera_ov8865_q8v18a.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_ov9724.so:system/vendor/lib/libmmcamera_ov9724.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_ov9724_foxconn.so:system/vendor/lib/libmmcamera_ov9724_foxconn.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_ov13850.so:system/vendor/lib/libmmcamera_ov13850.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_ov13850_sunny_p13v01h.so:system/vendor/lib/libmmcamera_ov13850_sunny_p13v01h.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_s5k3l1yx.so:system/vendor/lib/libmmcamera_s5k3l1yx.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_S5K4E1_13P1BA.so:system/vendor/lib/libmmcamera_S5K4E1_13P1BA.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_s5k4e1_foxconn_dc0301a.so:system/vendor/lib/libmmcamera_s5k4e1_foxconn_dc0301a.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_s5k4e1_liteon_13p1.so:system/vendor/lib/libmmcamera_s5k4e1_liteon_13p1.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_S5K4E1_SKUHF.so:system/vendor/lib/libmmcamera_S5K4E1_SKUHF.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_s5k4e1_sunny.so:system/vendor/lib/libmmcamera_s5k4e1_sunny.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_s5k4e1_sunny_132.so:system/vendor/lib/libmmcamera_s5k4e1_sunny_132.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_s5k9a1_liteon.so:system/vendor/lib/libmmcamera_s5k9a1_liteon.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_SKUAA_ST_gc0339.so:system/vendor/lib/libmmcamera_SKUAA_ST_gc0339.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_skuab_shinetech_gc0339.so:system/vendor/lib/libmmcamera_skuab_shinetech_gc0339.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_SKUAB_ST_s5k4e1.so:system/vendor/lib/libmmcamera_SKUAB_ST_s5k4e1.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_skuf_ov5648_p5v23c.so:system/vendor/lib/libmmcamera_skuf_ov5648_p5v23c.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_skuf_ov12830_p12v01c.so:system/vendor/lib/libmmcamera_skuf_ov12830_p12v01c.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_sp1628.so:system/vendor/lib/libmmcamera_sp1628.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_sunny_imx214_eeprom.so:system/vendor/lib/libmmcamera_sunny_imx214_eeprom.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_sunny_p5v23c_eeprom.so:system/vendor/lib/libmmcamera_sunny_p5v23c_eeprom.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_sunny_p12v01m_eeprom.so:system/vendor/lib/libmmcamera_sunny_p12v01m_eeprom.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_sunny_q5v22e_eeprom.so:system/vendor/lib/libmmcamera_sunny_q5v22e_eeprom.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_sunny_q5v41b_eeprom.so:system/vendor/lib/libmmcamera_sunny_q5v41b_eeprom.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_sunny_q8v18a_eeprom.so:system/vendor/lib/libmmcamera_sunny_q8v18a_eeprom.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_sunny_q13v04b_eeprom.so:system/vendor/lib/libmmcamera_sunny_q13v04b_eeprom.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_truly_cm7700_eeprom.so:system/vendor/lib/libmmcamera_truly_cm7700_eeprom.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_tuning.so:system/vendor/lib/libmmcamera_tuning.so \
    $(PATH_FILES)/vendor/lib/libmmcamera_wavelet_lib.so:system/vendor/lib/libmmcamera_wavelet_lib.so



PRODUCT_COPY_FILES += \
    $(PATH_FILES)/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
    $(PATH_FILES)/vendor/lib/libacdbmapper.so:system/vendor/lib/libacdbmapper.so \
    $(PATH_FILES)/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
    $(PATH_FILES)/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so \
    $(PATH_FILES)/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    $(PATH_FILES)/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
    $(PATH_FILES)/vendor/lib/libalarmservice_jni.so:system/vendor/lib/libalarmservice_jni.so \
    $(PATH_FILES)/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
    $(PATH_FILES)/vendor/lib/libaudioalsa.so:system/vendor/lib/libaudioalsa.so \
    $(PATH_FILES)/vendor/lib/libbtnv.so:system/vendor/lib/libbtnv.so \
    $(PATH_FILES)/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    $(PATH_FILES)/vendor/lib/libc2d30-a4xx.so:system/vendor/lib/libc2d30-a4xx.so \
    $(PATH_FILES)/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    $(PATH_FILES)/vendor/lib/libcalmodule_akm.so:system/vendor/lib/libcalmodule_akm.so \
    $(PATH_FILES)/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    $(PATH_FILES)/vendor/lib/libcneapiclient.so:system/vendor/lib/libcneapiclient.so \
    $(PATH_FILES)/vendor/lib/libCommandSvc.so:system/vendor/lib/libCommandSvc.so \
    $(PATH_FILES)/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    $(PATH_FILES)/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    $(PATH_FILES)/vendor/lib/libdisp-aba.so:system/vendor/lib/libdisp-aba.so \
    $(PATH_FILES)/vendor/lib/libDivxDrm.so:system/vendor/lib/libDivxDrm.so \
    $(PATH_FILES)/vendor/lib/lib-dplmedia.so:system/vendor/lib/lib-dplmedia.so \
    $(PATH_FILES)/vendor/lib/libdpmctmgr.so:system/vendor/lib/libdpmctmgr.so \
    $(PATH_FILES)/vendor/lib/libdpmfdmgr.so:system/vendor/lib/libdpmfdmgr.so \
    $(PATH_FILES)/vendor/lib/libdpmframework.so:system/vendor/lib/libdpmframework.so \
    $(PATH_FILES)/vendor/lib/libdrmfs.so:system/vendor/lib/libdrmfs.so \
    $(PATH_FILES)/vendor/lib/libdrmtime.so:system/vendor/lib/libdrmtime.so \
    $(PATH_FILES)/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    $(PATH_FILES)/vendor/lib/libdsnetutils.so:system/vendor/lib/libdsnetutils.so \
    $(PATH_FILES)/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    $(PATH_FILES)/vendor/lib/libExtendedExtractor.so:system/vendor/lib/libExtendedExtractor.so \
    $(PATH_FILES)/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so \
    $(PATH_FILES)/vendor/lib/libFileMux.so:system/vendor/lib/libFileMux.so \
    $(PATH_FILES)/vendor/lib/libFlacSwDec.so:system/vendor/lib/libFlacSwDec.so \
    $(PATH_FILES)/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    $(PATH_FILES)/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    $(PATH_FILES)/vendor/lib/libI420colorconvert.so:system/vendor/lib/libI420colorconvert.so \
    $(PATH_FILES)/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    $(PATH_FILES)/vendor/lib/lib-imscamera.so:system/vendor/lib/lib-imscamera.so \
    $(PATH_FILES)/vendor/lib/lib-imsdpl.so:system/vendor/lib/lib-imsdpl.so \
    $(PATH_FILES)/vendor/lib/lib-imsqimf.so:system/vendor/lib/lib-imsqimf.so \
    $(PATH_FILES)/vendor/lib/lib-imsrcs.so:system/vendor/lib/lib-imsrcs.so \
    $(PATH_FILES)/vendor/lib/lib-imss.so:system/vendor/lib/lib-imss.so \
    $(PATH_FILES)/vendor/lib/lib-imsSDP.so:system/vendor/lib/lib-imsSDP.so \
    $(PATH_FILES)/vendor/lib/lib-imsvt.so:system/vendor/lib/lib-imsvt.so \
    $(PATH_FILES)/vendor/lib/lib-imsxml.so:system/vendor/lib/lib-imsxml.so \
    $(PATH_FILES)/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    $(PATH_FILES)/vendor/lib/libjpegdhw.so:system/vendor/lib/libjpegdhw.so \
    $(PATH_FILES)/vendor/lib/libjpegehw.so:system/vendor/lib/libjpegehw.so \
    $(PATH_FILES)/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
    $(PATH_FILES)/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    $(PATH_FILES)/vendor/lib/liblocationservice.so:system/vendor/lib/liblocationservice.so \
    $(PATH_FILES)/vendor/lib/libloc_ext.so:system/vendor/lib/libloc_ext.so \
    $(PATH_FILES)/vendor/lib/liblowi_client.so:system/vendor/lib/liblowi_client.so \
    $(PATH_FILES)/vendor/lib/libmm-abl.so:system/vendor/lib/libmm-abl.so \
    $(PATH_FILES)/vendor/lib/libmm-abl-oem.so:system/vendor/lib/libmm-abl-oem.so \
    $(PATH_FILES)/vendor/lib/libmm-color-convertor.so:system/vendor/lib/libmm-color-convertor.so \
    $(PATH_FILES)/vendor/lib/libmmipl.so:system/vendor/lib/libmmipl.so \
    $(PATH_FILES)/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
    $(PATH_FILES)/vendor/lib/libmmosal.so:system/vendor/lib/libmmosal.so \
    $(PATH_FILES)/vendor/lib/libmmparser.so:system/vendor/lib/libmmparser.so \
    $(PATH_FILES)/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
    $(PATH_FILES)/vendor/lib/libmmrtpdecoder.so:system/vendor/lib/libmmrtpdecoder.so \
    $(PATH_FILES)/vendor/lib/libmmrtpencoder.so:system/vendor/lib/libmmrtpencoder.so \
    $(PATH_FILES)/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    $(PATH_FILES)/vendor/lib/libNimsWrap.so:system/vendor/lib/libNimsWrap.so \
    $(PATH_FILES)/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    $(PATH_FILES)/vendor/lib/libOmxAacDec.so:system/vendor/lib/libOmxAacDec.so \
    $(PATH_FILES)/vendor/lib/libomx_amrdec_sharedlibrary.so:system/vendor/lib/libomx_amrdec_sharedlibrary.so \
    $(PATH_FILES)/vendor/lib/libomx_amrenc_sharedlibrary.so:system/vendor/lib/libomx_amrenc_sharedlibrary.so \
    $(PATH_FILES)/vendor/lib/libOmxEvrcDec.so:system/vendor/lib/libOmxEvrcDec.so \
    $(PATH_FILES)/vendor/lib/libOmxMux.so:system/vendor/lib/libOmxMux.so \
    $(PATH_FILES)/vendor/lib/libOmxQcelp13Dec.so:system/vendor/lib/libOmxQcelp13Dec.so \
    $(PATH_FILES)/vendor/lib/libomx_sharedlibrary.so:system/vendor/lib/libomx_sharedlibrary.so \
    $(PATH_FILES)/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    $(PATH_FILES)/vendor/lib/libprdrmdecrypt.so:system/vendor/lib/libprdrmdecrypt.so \
    $(PATH_FILES)/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    $(PATH_FILES)/vendor/lib/libqc-opt.so:system/vendor/lib/libqc-opt.so \
    $(PATH_FILES)/vendor/lib/libqct_resampler.so:system/vendor/lib/libqct_resampler.so \
    $(PATH_FILES)/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    $(PATH_FILES)/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
    $(PATH_FILES)/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    $(PATH_FILES)/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    $(PATH_FILES)/vendor/lib/libqmi_client_helper.so:system/vendor/lib/libqmi_client_helper.so \
    $(PATH_FILES)/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    $(PATH_FILES)/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    $(PATH_FILES)/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    $(PATH_FILES)/vendor/lib/libqmi_csvt_srvc.so:system/vendor/lib/libqmi_csvt_srvc.so \
    $(PATH_FILES)/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    $(PATH_FILES)/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    $(PATH_FILES)/vendor/lib/libqomx_jpegdec.so:system/vendor/lib/libqomx_jpegdec.so \
    $(PATH_FILES)/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so \
    $(PATH_FILES)/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
    $(PATH_FILES)/vendor/lib/libquipc_os_api.so:system/vendor/lib/libquipc_os_api.so \
    $(PATH_FILES)/vendor/lib/lib-rcsimssjni.so:system/vendor/lib/lib-rcsimssjni.so \
    $(PATH_FILES)/vendor/lib/lib-rcsjni.so:system/vendor/lib/lib-rcsjni.so \
    $(PATH_FILES)/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
    $(PATH_FILES)/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    $(PATH_FILES)/vendor/lib/librpmb.so:system/vendor/lib/librpmb.so \
    $(PATH_FILES)/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    $(PATH_FILES)/vendor/lib/lib-rtpcommon.so:system/vendor/lib/lib-rtpcommon.so \
    $(PATH_FILES)/vendor/lib/lib-rtpcore.so:system/vendor/lib/lib-rtpcore.so \
    $(PATH_FILES)/vendor/lib/lib-rtpdaemoninterface.so:system/vendor/lib/lib-rtpdaemoninterface.so \
    $(PATH_FILES)/vendor/lib/lib-rtpsl.so:system/vendor/lib/lib-rtpsl.so \
    $(PATH_FILES)/vendor/lib/libsc-a2xx.so:system/vendor/lib/libsc-a2xx.so \
    $(PATH_FILES)/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
    $(PATH_FILES)/vendor/lib/libscale.so:system/vendor/lib/libscale.so \
    $(PATH_FILES)/vendor/lib/libscve.so:system/vendor/lib/libscve.so \
    $(PATH_FILES)/vendor/lib/libSHIMDivxDrm.so:system/vendor/lib/libSHIMDivxDrm.so \
    $(PATH_FILES)/vendor/lib/libsrsprocessing.so:system/vendor/lib/libsrsprocessing.so \
    $(PATH_FILES)/vendor/lib/libssd.so:system/vendor/lib/libssd.so \
    $(PATH_FILES)/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so \
    $(PATH_FILES)/vendor/lib/libthermalioctl.so:system/vendor/lib/libthermalioctl.so \
    $(PATH_FILES)/vendor/lib/libTimeService.so:system/vendor/lib/libTimeService.so \
    $(PATH_FILES)/vendor/lib/libtzplayready.so:system/vendor/lib/libtzplayready.so \
    $(PATH_FILES)/vendor/lib/libulp2.so:system/vendor/lib/libulp2.so \
    $(PATH_FILES)/vendor/lib/libvoice-svc.so:system/vendor/lib/libvoice-svc.so \
    $(PATH_FILES)/vendor/lib/libwifiscanner.so:system/vendor/lib/libwifiscanner.so \
    $(PATH_FILES)/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    $(PATH_FILES)/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    $(PATH_FILES)/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    $(PATH_FILES)/vendor/lib/libxml.so:system/vendor/lib/libxml.so \
    $(PATH_FILES)/vendor/lib/libxtadapter.so:system/vendor/lib/libxtadapter.so \
    $(PATH_FILES)/vendor/lib/libxt_native.so:system/vendor/lib/libxt_native.so \
    $(PATH_FILES)/vendor/lib/libxtwifi_ulp_adaptor.so:system/vendor/lib/libxtwifi_ulp_adaptor.so \
    $(PATH_FILES)/vendor/lib/libxtwifi_zpp_adaptor.so:system/vendor/lib/libxtwifi_zpp_adaptor.so

PRODUCT_COPY_FILES += \
    $(PATH_FILES)/vendor/media/LMspeed_508.emd:system/vendor/media/LMspeed_508.emd \
    $(PATH_FILES)/vendor/media/PFFprec_600.emd:system/vendor/media/PFFprec_600.emd

# Xbin
PRODUCT_COPY_FILES += \
    $(PATH_FILES)/xbin/qlogd:system/xbin/qlogd
